### ISSUE TITLE
Tracked entity instance search tree fixed height

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#1]
In search for TEI screen, detailed search, the org unit tree must have a fixed height. Currently it expands forever as you expand org units in the hierarchy, making it hard to get to the detailed search input fields.

![out](https://cloud.githubusercontent.com/assets/908206/16414054/bdfd8cbc-3d35-11e6-9caa-338124d1b493.png)

**Comment by abyot** [comment]
Fixed. 9515097f94f11d6852f4ef09e9dea642b6306796
