### ISSUE TITLE
Dashboard: Show loading indicator until all widgets are loaded

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#10]
Show a loading indicator on the tracker dashboard page until all widgets are loaded. Display all widgets in a loaded state.

**Comment by abyot** [comment]
@larshelge with the "dancing around", are you referring to all the widgets not loading at the same time?

**Comment by jijukjose** [comment]
Show indicator on the page until all the widgets are loaded. The navigation bar (top menu) should be shown as soon as possible but the widgets should be displayed together when all of them are loaded.

**Comment by jijukjose** [comment]
A loading indicator is shown while the meta data and dashboard components are loading with an appropriate loading message.
