### ISSUE TITLE
Messaging dashboard widget

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#13]
Introduce a messaging widget for the tracker dashboard. The messaging widget should utilize the new program message Web API. The widget should fetch contact information such as phone number and email address from the attributes of the current tracked entity instance. 

The widget should offer to send messages over SMS or email. It should allow for optionally specifying a phone number or email manually.

API docs found [here](http://dhis2.github.io/dhis2-docs/master/en/developer/html/webapi_program_messages.html).

**Comment by jijukjose** [comment]
Currently working on this.

**Comment by jijukjose** [comment]
Implemented and checked in.
