### ISSUE TITLE
Capture coordinate for enrollment

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#14]
Add support for capturing coordinate (location) for an enrollment.

Introduce a new property "captureCoordinates" (Boolean) for class Program.

When enabled, the enrollment screen should offer to capture the location. This is similar to the feature for capturing coordinate for program stage.

**Comment by abyot** [comment]
done.

**Comment by erlingfjelstad** [comment]
Possible improvement: If you search for a place, say, Ngelehun in the search box and then press the capture coordinates button. When the user is being sent back to enrollment screen, the UI should show "Ngelehun" next to/below the coordinates.

**Comment by erlingfjelstad** [comment]
UI Inconsistency between browsers: 
In Firefox the user can see a button which can bump/decrease the latitude and longitude. This button is not visible in Chrome. In my opinion, the bump/decrease button doesn't make sense and shouldn't be there in Firefox. 

username: android
password: Android123

See attachments. 
Firefox:
![skjermbilde 2016-09-27 kl 10 56 45](https://cloud.githubusercontent.com/assets/4091353/18866686/5f23ce32-84a1-11e6-9e12-44c50cb6a628.png)

Chrome: 
![skjermbilde 2016-09-27 kl 10 56 58](https://cloud.githubusercontent.com/assets/4091353/18866701/6d9e2282-84a1-11e6-981a-8d112bf2f2f5.png)
