### ISSUE TITLE
Improve Advanced search options UI

### ISSUE THREAD

**Issue by jijukjose** [dhis2/tracker-capture-app#17]
The advanced search option window has unnecessary white space between the org unit tree and the input fields. This causes an extra scroll bar in the window.

![image](https://cloud.githubusercontent.com/assets/3884454/18543267/37f31064-7b2f-11e6-9925-2d0d66cdb4a1.png)

**Comment by jijukjose** [comment]
Increase the size on the drop-down menu to chose Is/Range for age and birth date.

**Comment by abyot** [comment]
This is fixed.

**Comment by erlingfjelstad** [comment]
Minor UI improvement: Scroll bar is visible even though the "adavanced search options UI" isn't scrollable. 
username: android
password: Android123

Browser(s): Firefox, Chrome

See attachement

![skjermbilde 2016-09-27 kl 10 25 46](https://cloud.githubusercontent.com/assets/4091353/18865691/dc16da42-849c-11e6-9213-baed7ff597e4.png)
