### ISSUE TITLE
Vertical align Yes/No radio buttons

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#2]
For data elements of type Yes/No, vertical align the radio buttons inside the parent div. Currently it is too close to the bottom.

![yesno](https://cloud.githubusercontent.com/assets/908206/17373588/2494454e-59a9-11e6-8b22-78bd2703e7a4.png)

**Comment by abyot** [comment]
@larshelge  @jijukjose This is now fixed.

![image](https://cloud.githubusercontent.com/assets/4967749/17435198/6a279f7c-5b0f-11e6-98a9-652978453484.png)
