### ISSUE TITLE
Timeline data entry is not scrollable when moved to right hand side in the TEI dashboard

### ISSUE THREAD

**Issue by erlingfjelstad** [dhis2/tracker-capture-app#21]
The user is not able to scroll down the page when moving the timeline data entry widget from left hand side to right hand side. On my testing I placed it above the "Profile" widget and I couldn't scroll the page. 

username: android
password: Android123
Browser: Firefox v. 48.0.2

See attachement.

<img width="1120" alt="skjermbilde 2016-09-27 kl 10 34 21" src="https://cloud.githubusercontent.com/assets/4091353/18866152/dccd78c2-849e-11e6-9ae7-94f6ae30744f.png">

**Comment by abyot** [comment]
@erlingfjelstad 

This is because the left column is pinned.
