### ISSUE TITLE
Form printing issues with drop down elements.

### ISSUE THREAD

**Issue by VladislavAlfredov** [dhis2/tracker-capture-app#26]
When printing a form, during registration with drop down elements (Example: Gender), with hint/description ("Select or search from the list"). 

Problems: 
- The hint appears above the field. 
- Also if there is a value it is printed in the place of the hint (?).
- There is an extra input field.
- There is a weird dot after "Gender".
-  The label "Gender" is not aligned with the input field (Maybe it is aligned with both fields ??).

Seems to happen for TrackedEnitityAttributes for TrackedEntitiyInstance.

Steps to reproduce:
1.Open Tracker capture app
2.Go to Sierra Leonne>Bo>Badjia>Ngelehun CHC, Program: Child programme
3. Click "Register"
4. Click "Print Form"
5. Result: [Tracker Capture.pdf](https://github.com/dhis2/tracker-capture-app/files/510593/Tracker.Capture.pdf)

The drop down hint is misplaced. Also the choice for the drop down (if selected) replaces the hint.

**Comment by jijukjose** [comment]
This is fixed and pushed.
