### ISSUE TITLE
Save and continue loading indicator

### ISSUE THREAD

**Issue by Bekkalizer** [dhis2/tracker-capture-app#30]
When registering a tracked entity instance and clicking "Save and continue", the registration sometimes takes a few seconds. During this time no indication is given that the save is actually commencing - and it might be tempting to try clicking the"Save and continue" button a second time, a bit harder.

**Comment by jijukjose** [comment]
when saving is in progress, a loading indicator (spinner) is displayed and the buttons are disabled.
