### ISSUE TITLE
Check the orgunit start and end date while registering/editing the enrollment/incident date

### ISSUE THREAD

**Issue by jijukjose** [dhis2/tracker-capture-app#34]
When the enrollment/incident date is edited, the entered date should fall within the start and end date of the orgunit.

**Comment by jijukjose** [comment]
Added code for the required check -
https://github.com/dhis2/tracker-capture-app/commit/3904f229b71099086d11d268ba36585eb7117191.

An error message is popped up when the current date is not within the start and end date of the orgunit.

**Comment by abyot** [comment]
This is now moved to Jira.
