### ISSUE TITLE
Yes only fields not rendered pretty

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#5]
* In the Tabular data entry widget on dashboard, for data elements of value type Yes only. In the tabular view, yes values are rendered as "true". Should be rendered as "Yes".

![true](https://cloud.githubusercontent.com/assets/908206/17382309/844a97f0-59d0-11e6-8fa3-2bd0e1f7af3c.png)

* This also applies to the audit log dialog for the Tabular data entry widget.

![audit](https://cloud.githubusercontent.com/assets/908206/17382657/358edcf0-59d2-11e6-8af8-eba3fae49196.png)

**Comment by abyot** [comment]
@larshelge  this is now fixed.
