### ISSUE TITLE
Notes in tabular data entry cut too early

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#6]
In the Tabular data entry widget, Notes section, the note text is cut off at 100px not matter how much screen space is available.

Instead use all of the available screen space. This will give the end user a better overview of the notes at a glance.

**Comment by larshelge** [comment]
This could potentially be done with CSS overflow:hidden.

**Comment by jijukjose** [comment]
Fixed and backported to 2.24.
