### ISSUE TITLE
Edit profile fails with unknown fields

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#7]
Tracker dashboard, profile widget. With certain people, when clicking save to edit the profile information, the PUT request fails with "Unrecognized fields". The client tries to send fields which looks like UIDs, e.g. "iggSfNDnsCw".

Response:

{"httpStatus":"Internal Server Error","httpStatusCode":500,"status":"ERROR","message":"Unrecognized field \"iggSfNDnsCw\" (class org.hisp.dhis.dxf2.events.trackedentity.TrackedEntityInstance), not marked as ignorable (9 known properties: \"trackedEntityInstance\", \"lastUpdated\", \"attributes\", \"orgUnit\", \"relationships\", \"trackedEntity\", \"enrollments\", \"created\", \"inactive\"])\n at [Source: org.apache.catalina.connector.CoyoteInputStream@340dab3; line: 1, column: 207] (through reference chain: org.hisp.dhis.dxf2.events.trackedentity.TrackedEntityInstance[\"iggSfNDnsCw\"])"}

Can be reproduced here:

https://play.dhis2.org/demo/dhis-web-tracker-capture/index.html#/dashboard?tei=foc5zag6gbE&program=ur1Edk5Oe2n&ou=DiszpKrYNg8

**Comment by abyot** [comment]
@larshelge this is now fixed.
