### ISSUE TITLE
Program message widget

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#9]
Add a new messaging widget. It should:

- Select the contact information directly from the tracked entity attributes (profile).
- Allow for selecting between sending over SMS and email (when available).
- Allow for entering phone number or email directly.

This widget should use the program message Web API resource.

http://dhis2.github.io/dhis2-docs/master/en/developer/html/webapi_program_messages.html

**Comment by abyot** [comment]
@larshelge  is this a duplicate of #13

**Comment by jijukjose** [comment]
This is implemented as part of - https://github.com/dhis2/tracker-capture-app/issues/13
